#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders
mkdir -p /config/logs

if [[ ! -f /config/nzbhydra.yml ]]; then
    cp /defaults/nzbhydra.yml /config/nzbhydra.yml
fi

# permissions
lsiown -R abc:abc \
    /config
