#!/usr/bin/with-contenv bash

# make our folders
mkdir -p /config/logs

if [[ ! -f /config/nzbhydra.yml ]]; then
    cp /defaults/nzbhydra.yml /config/nzbhydra.yml
fi

# permissions
chmod +x /app/nzbhydra2/bin/nzbhydra2
lsiown -R abc:abc /config